config/routes.rb
Rails.application.routes.draw do

  resources :url_weight_rules
  resources :filter_words
  resources :wx_documents
  resources :hot_words

  resources :bd_documents do
    get 'search', on: :collection
  end

  resources :web_pages

  resources :apps do
    get 'docs', on: :collection
    get 'my_docs', on: :collection
    get 'npy_docs', on: :collection
    get 'add_my_doc', on: :collection
    get 'remove_my_doc', on: :collection
  end

  root to: "apps#index"

end

app/controllers/bd_documents_controller.rb
class BdDocumentsController < ApplicationController
  before_action -> { @navbar = :bd_document }
  
  def index
  end

  def search
    @results = BaiduKeywordSearchWorker.new.perform params["keywords"]
  end
end

app/helpers/bd_documents_helper.rb
module BdDocumentsHelper
end

app/views/bd_documents/index.html.erb
<div class="row">
  <div class="row pad-ver mar-btm bg-trans-dark">
    <form class="col-xs-12 col-sm-10 col-sm-offset-1 pad-hor" method="get" action="<%= search_bd_documents_path %>">
      <input type="text" placeholder="输入关键字" class="form-control input-lg" name="keywords">
    </form>
  </div>
</div>

app/views/bd_documents/search.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th>文章标题</th>
      <th>关键字</th>
      <th>发布时间</th>
    </tr>
  </thead>
  <tbody>
  <% @results["search_content"].each do |doc| %>
    <tr>
      <td><%= link_to doc["title"], doc["url"],target: "_blank" %></td>
      <td><%= doc["keyword"] %></td>
      <td><%= doc["crawl_at"] %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to "返回", bd_documents_path, class: 'btn btn-primary' %>