config/routes.rb
Rails.application.routes.draw do

  resources :url_weight_rules
  resources :filter_words
  resources :wx_documents
  resources :hot_words

  resources :bd_documents do
    get 'search', on: :collection
  end

  resources :web_pages

  resources :apps do
    get 'docs', on: :collection
    get 'my_docs', on: :collection
    get 'npy_docs', on: :collection
    get 'add_my_doc', on: :collection
    get 'remove_my_doc', on: :collection
  end

  root to: "apps#index"

end

app/models/filter_word.rb
# == Schema Information
#
# Table name: filter_words
#
#  id         :integer          not null, primary key
#  word       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class FilterWord < ActiveRecord::Base
end

app/controllers/filter_words_controller.rb
class FilterWordsController < ApplicationController

  layout "app"

  def index
    @filter_words = FilterWord.page params[:page]
  end

  def new
    @filter_word = FilterWord.new
  end

  def create
    @filter_word = FilterWord.new resource_params
    @filter_word.save
    respond_with @filter_word, location: -> { ok_url_or_default filter_words_path }
  end

  def edit
    @filter_word = FilterWord.find_by(id: params[:id]) if  params[:id]
    respond_with @filter_word, location: -> { ok_url_or_default filter_words_path } unless @filter_word
  end

  def update
    @filter_word = FilterWord.find_by(id: params[:id]) if params[:id]
    @filter_word.update resource_params
    respond_with @filter_word, location: -> { ok_url_or_default filter_words_path }
  end

  def destroy
    @filter_word = FilterWord.find_by(id: params[:id]) if params[:id]
    @filter_word.destroy
    respond_with @filter_word, location: -> { ok_url_or_default filter_words_path }
  end

protected
  def resource_params
    params[:filter_word].permit(:word) if params[:filter_word]
  end
end

app/helpers/filter_words_helper.rb
module FilterWordsHelper
end

app/views/filter_words/_form.html.erb
<%= simple_form_for(@filter_word) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :word, label: '名称' %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, value: '更新' %>
      <%= link_to '回退', filter_words_path, class: 'btn btn-default btn-active-purple active' %>
    </div>
<% end %>

app/views/filter_words/edit.html.erb
<h1>修改</h1>


<%= render 'form' %>

app/views/filter_words/index.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-hover table-vcenter">
  <thead>
  <tr>
    <th><%=h FilterWord, :word %></th>
    <th>操作</th>
  </tr>
  </thead>

  <tbody>
  <% @filter_words.each do |word| %>
      <tr>
        <td><%= word.word %></td>
        <td>
          <%= link_to '修改', edit_filter_word_path(word, ok_url: request.fullpath) %>
          <%= link_to '删除', filter_word_path(word, ok_url: request.fullpath), method: :delete, data: {confirm: 'Are you sure?'} %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to '新增', new_filter_word_path, class: 'btn btn-default btn-active-purple active' %>

app/views/filter_words/new.html.erb
<h1>新增</h1>

<%= render 'form' %>