config/routes.rb
Rails.application.routes.draw do

  resources :url_weight_rules
  resources :filter_words
  resources :wx_documents
  resources :hot_words

  resources :bd_documents do
    get 'search', on: :collection
  end

  resources :web_pages

  resources :apps do
    get 'docs', on: :collection
    get 'my_docs', on: :collection
    get 'npy_docs', on: :collection
    get 'add_my_doc', on: :collection
    get 'remove_my_doc', on: :collection
  end

  root to: "apps#index"

end

app/models/url_weight_rule.rb
# == Schema Information
#
# Table name: url_weight_rule
#
#  id         :integer          not null, primary key
#  url        :string(200)
#  weight     :float(53)
#  source     :string(300)
#  channel    :string(300)
#  created_at :datetime
#  updated_at :datetime
#

class UrlWeightRule < ActiveRecord::Base
  self.table_name = "url_weight_rule"
end

app/controllers/url_weight_rules_controller.rb
class UrlWeightRulesController < ApplicationController
  layout "app"
  before_action :set_url_weight_rule, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @url_weight_rules = UrlWeightRule.all
    respond_with(@url_weight_rules)
  end

  def show
    respond_with(@url_weight_rule)
  end

  def new
    @url_weight_rule = UrlWeightRule.new
    respond_with(@url_weight_rule)
  end

  def edit
  end

  def create
    @url_weight_rule = UrlWeightRule.new(url_weight_rule_params)
    @url_weight_rule.save
    respond_with(@url_weight_rule)
  end

  def update
    @url_weight_rule.update(url_weight_rule_params)
    respond_with(@url_weight_rule)
  end

  def destroy
    @url_weight_rule.destroy
    respond_with(@url_weight_rule)
  end

  private
  def set_url_weight_rule
    @url_weight_rule = UrlWeightRule.find(params[:id])
  end

  def url_weight_rule_params
    params.require(:url_weight_rule).permit(:url, :weight, :source, :channel)
  end
end

app/helpers/url_weight_rules_helper.rb
module UrlWeightRulesHelper
end

app/views/url_weight_rules/_form.html.erb
<%= simple_form_for(@url_weight_rule) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :url, label: 'URL' %>
      <%= f.input :weight, label: '权重' %>
      <%= f.input :source, label: '来源' %>
      <%= f.input :channel, label: '频道' %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, value: '更新' %>
      <%= link_to '回退', url_weight_rules_path, class: 'btn btn-default btn-active-purple active' %>
    </div>
<% end %>

app/views/url_weight_rules/index.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-hover table-vcenter">
  <thead>
  <tr>
    <th>Url</th>
    <th>权重</th>
    <th>来源</th>
    <th>频道</th>
    <th colspan="3">操作</th>
  </tr>
  </thead>

  <tbody>
  <% @url_weight_rules.each do |url_weight_rule| %>
      <tr>
        <td><%= url_weight_rule.url %></td>
        <td><%= url_weight_rule.weight %></td>
        <td><%= url_weight_rule.source %></td>
        <td><%= url_weight_rule.channel %></td>
        <td><%= link_to '修改', edit_url_weight_rule_path(url_weight_rule) %></td>
        <td><%= link_to '删除', url_weight_rule, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to '新增', new_url_weight_rule_path, class: 'btn btn-default btn-active-purple active' %>

app/views/url_weight_rules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @url_weight_rule.url %>
</p>

<p>
  <strong>权重:</strong>
  <%= @url_weight_rule.weight %>
</p>

<p>
  <strong>来源:</strong>
  <%= @url_weight_rule.source %>
</p>

<p>
  <strong>频道:</strong>
  <%= @url_weight_rule.channel %>
</p>

<%= link_to '修改', edit_url_weight_rule_path(@url_weight_rule) %> |
<%= link_to '回退', url_weight_rules_path, class: 'btn btn-default btn-active-purple active' %>