config/routes.rb
Rails.application.routes.draw do

  resources :url_weight_rules
  resources :filter_words
  resources :wx_documents
  resources :hot_words

  resources :bd_documents do
    get 'search', on: :collection
  end

  resources :web_pages

  resources :apps do
    get 'docs', on: :collection
    get 'my_docs', on: :collection
    get 'npy_docs', on: :collection
    get 'add_my_doc', on: :collection
    get 'remove_my_doc', on: :collection
  end

  root to: "apps#index"

end

app/models/filter_word.rb
# == Schema Information
#
# Table name: filter_words
#
#  id         :integer          not null, primary key
#  word       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class FilterWord < ActiveRecord::Base
end

app/models/hot_word.rb
class HotWord < ActiveRecord::Base

  establish_connection :database_baidu

end

app/models/my_page.rb
# == Schema Information
#
# Table name: my_pages
#
#  id         :integer          not null, primary key
#  page_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class MyPage < ActiveRecord::Base
end

app/models/page_keyword.rb
# == Schema Information
#
# Table name: page_keywords
#
#  id       :integer          not null, primary key
#  page_id  :integer
#  keywords :text(65535)
#

class PageKeyword < ActiveRecord::Base
end

app/models/page_rank.rb
# == Schema Information
#
# Table name: page_rank
#
#  id          :integer          not null, primary key
#  page_id     :integer
#  weight      :float(53)
#  publishtime :string(30)
#

class PageRank< ActiveRecord::Base
  self.table_name = "page_rank"
end

app/models/url_weight_rule.rb
# == Schema Information
#
# Table name: url_weight_rule
#
#  id         :integer          not null, primary key
#  url        :string(200)
#  weight     :float(53)
#  source     :string(300)
#  channel    :string(300)
#  created_at :datetime
#  updated_at :datetime
#

class UrlWeightRule < ActiveRecord::Base
  self.table_name = "url_weight_rule"
end

app/models/web_page.rb
class WebPage < ActiveRecord::Base
end

app/models/web_page_meta_data.rb
# == Schema Information
#
# Table name: webpage_metadata_parser
#
#  id         :integer          not null, primary key
#  url        :string(600)
#  json       :text(4294967295)
#  updated_at :string(30)
#

class WebPageMetaData < ActiveRecord::Base
  self.table_name = "webpage_metadata_parser"

  has_many :page_ranks, foreign_key: :page_id, primary_key: :id, class_name: "PageRank"
  has_many :my_pages, foreign_key: :page_id, primary_key: :id, class_name: "MyPage"
  has_many :page_keywords, foreign_key: :page_id, primary_key: :id, class_name: "PageKeyword"
end

app/models/wx_document.rb
class WxDocument < ActiveRecord::Base
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  paginated_action only: [:docs, :my_docs, :npy_docs]

  def index
  end

  def docs
    query = WebPageMetaData.where("webpage_metadata_parser.id in (select min(id) from webpage_metadata_parser group by webpage_metadata_parser.title)")
                .joins("INNER JOIN url_weight_rule ON url_weight_rule.channel = '体育' AND url_weight_rule.domain=replace((replace((SUBSTRING_INDEX(SUBSTRING_INDEX(REPLACE( webpage_metadata_parser.url , '//', ''), '/', 1), '*', -2)), 'http:','')),'https:','') ")
    query = query.where 'title like ?', "%#{params[:title]}%" if params[:title] && !params[:title].empty?
    if  params[:order] && params[:order] == 'time'
      query = query.order('publish_time desc')
    end
    query = query.includes(:page_keywords)
    @apps= query.page(@kp_page).per(@kp_per_page)
    respond_with query_docs @apps
  end

  def my_docs
    query = WebPageMetaData.joins(:my_pages)
    query = query.where('json like ?', "%#{params[:title]}%") if (params[:title])
    query = query.order('my_pages.created_at desc')
    query = query.includes(:page_keywords)
    @apps= query.page(@kp_page).per(@kp_per_page)
    respond_with query_docs(@apps)
  end

  def add_my_doc
    page_id = params[:page_id]
    page = MyPage.find_or_initialize_by page_id: page_id
    page.save
    respond_with page
  end

  def remove_my_doc
    page_id = params[:page_id]
    page = MyPage.find_by page_id: page_id
    page.destroy if page
    respond_with page
  end

  def npy_docs
    @kp_page = 0 if @kp_per_page.nil?
    @kp_per_page = 5 if @kp_per_page.nil?
    @apps= query_npy(params['title'], (@kp_page-1) * @kp_per_page, @kp_per_page)
    @res = Array.new

    def @apps.total_count
      self['numFound']
    end

    def @apps.current_page
      self['start']/5 + 1
    end

    def @apps.length
      self['docs'].length
    end

    @apps['docs'].each do |map|
      tmp = Hash.new
      tmp['url'] = map['url']
      tmp['title'] = map['title'].remove /\|.*/, /_.*/
      tmp['content'] = map['content'].strip.truncate(100)
      tmp['source'] = query_source(map['url'])
      tmp['updated_at'] = DateTime.parse(map['tstamp']).strftime('%Y-%m-%d %H:%M:%S')
      tmp['id'], tmp['keywords'] = query_keywords_url map['url']
      @res.append tmp
      begin
      rescue
      end
    end
    respond_with @res
  end
end


private
def query_docs(docs)
  @res = Array.new
  docs.each do |doc|
    tmp = Hash.new
    tmp['id'] = doc.id
    tmp['updated_at'] = doc.publish_time.empty? ? '' :  DateTime.parse(doc.publish_time).strftime('%Y-%m-%d %H:%M:%S')
    tmp['url'] = doc.url
    tmp['title'] = doc.title.remove /\|.*/, /_.*/
    tmp['content'] = doc.main_body.strip.truncate(100)
    tmp['source'] = query_source(doc.url)
    tmp['keywords'] = doc.page_keywords.first.nil? ? '' : fitler_words(doc.page_keywords.first.keywords.split(','))
    @res.append tmp
  end
  @res
end

def query_source(url)
  return '' if url.empty?
  # rule = UrlWeightRule.where("'"+url+ "'"+" LIKE concat('"+'%%'+"',url,'"+'%%'+"')", "").try(:first)
  rule = UrlWeightRule.where(" url like '%#{URI.parse(url).hostname}%'").try(:first)
  rule.nil? ? '' : rule.source
end

def query_keywords_url(url)
  page = WebPageMetaData.find_by(url: url)
  return nil unless page
  keyword = page.page_keywords.first
  [page.id, keyword.nil? ? '' : fitler_words(keyword.keywords.split(','))]
end

def query_npy(title, start, rows)
  url = "http://139.129.194.51:8983/solr/collection1/select?q=女朋友,女友,#{title}&start=#{start}&rows=#{rows}&wt=json&sort=tstamp+desc&indent=true"
  print url
  res = RestClient.get URI.encode(url)
  json = JSON.parse res
  json['response']
end

def fitler_words(keywords)
  return '' unless keywords
  filter_words = FilterWord.all
  filter_words.each do |words|
    keywords.delete words.word if keywords.include? words.word
  end
  return keywords
end

app/controllers/hot_words_controller.rb
class HotWordsController < ApplicationController
  layout 'app'
  def index
    @search_date = params['data_date'] ? params['data_date'] : Time.now.strftime("%Y%m%d")
    @hot_words = HotWord.where("data_date = #{ @search_date }").select(:content, :url, :data_date).distinct
  end
end

app/controllers/web_pages_controller.rb
class WebPagesController < ApplicationController
  before_action -> { @navbar = :wx_page }

  def index
     @pages = WebPage.all.order("fetchTime desc").page params[:page]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/bd_documents_helper.rb
module BdDocumentsHelper
end

app/helpers/filter_words_helper.rb
module FilterWordsHelper
end

app/helpers/hot_words_helper.rb
module HotWordsHelper
end

app/helpers/url_weight_rules_helper.rb
module UrlWeightRulesHelper
end

app/helpers/web_pages_helper.rb
module WebPagesHelper
end

app/helpers/wx_documents_helper.rb
module WxDocumentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WXOA</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<script>
    angular.bootstrap(document, ['app']);
</script>
</body>
</html>

app/views/layouts/application_demo.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>新华社采集展现系统</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% unless content_for?(:skip_navbar) %>
 <nav class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
         <%= link_to "新华社采集展现系统", "#", class: "navbar-brand" %>
      </div>

      <div class="collapse navbar-collapse">
        <%= fume_nav @navbar do |n| %>
        <ul class="nav navbar-nav">
          <%= n.li_tag :wx_document do %>
            <%= link_to wx_documents_path do %><i class="fa fa-download fa-fw"></i> 微信数据 <% end %>
          <% end %>

          <%= n.li_tag :web_page do %>
            <%= link_to web_pages_path do %><i class="fa fa-download fa-fw"></i> 网媒数据 <% end %>
          <% end %>

          <%= n.li_tag :bd_document do %>
            <%= link_to bd_documents_path do %><i class="fa fa-download fa-fw"></i> 搜索引擎数据 <% end %>
          <% end %>

        </ul>
        <% end %>

      </div><!-- /.collapse navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
<% end %>

<div class="container">
  <% flash.each do |type, message| %>
    <div class="alert <%= bootstrap_alert(type) %> fade in">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
  <% end %>

  <%= yield %>

  <footer>
  </footer>
</div>

</body>
</html>